MODES = [
            {'id': 1, 'description': 'Standard traffic light',
                'sequence': [
                    (0,0,1),
                    (1,0,0),
                    (0,1,0),
                    (0,0,1),
                    (1,0,0),
                    (0,1,0),
                    (0,0,1),
                  ]
            },
            {'id': 2, 'description': 'British traffic light',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (1,0,0),
                    (0,1,0),
                    (0,0,1),
                    (0,1,1),
                    (1,0,0),
                  ]
            },
            {'id': 3, 'description': 'Red-Yellow-Green All Flash',
                'sequence': [
                    (0,0,1),
                    (0,1,0),
                    (1,0,0),
                    (0,0,0),
                    (1,1,1),
                    (0,0,0),
                    (1,1,1),
                  ]
            },
            {'id': 4, 'description': 'Red-Yellow-Green Up-Down',
                'sequence': [
                    (0,0,1),
                    (0,1,0),
                    (1,0,0),
                    (0,1,0),
                    (0,0,1),
                    (0,1,0),
                    (1,0,0),
                  ]
            },
            {'id': 5, 'description': 'Old US Traffic Light',
                'sequence': [
                    (0,0,1),
                    (0,1,0),
                    (1,0,0),
                    (0,1,0),
                    (0,0,1),
                    (0,1,0),
                    (1,0,0),
                  ]
            },
            {'id': 6, 'description': 'Red Light Flashing Only',
                'sequence': [
                    (0,0,1),
                    (0,0,0),
                    (0,0,1),
                    (0,0,0),
                    (0,0,1),
                    (0,0,0),
                    (0,0,1),
                  ]
            },
            {'id': 7, 'description': 'Yellow Light Flashing Only',
                'sequence': [
                    (0,1,0),
                    (0,0,0),
                    (0,1,0),
                    (0,0,0),
                    (0,1,0),
                    (0,0,0),
                    (0,1,0),
                  ]
            },
            {'id': 8, 'description': 'Green Light Flashing Only',
                'sequence': [
                    (1,0,0),
                    (0,0,0),
                    (1,0,0),
                    (0,0,0),
                    (1,0,0),
                    (0,0,0),
                    (1,0,0),
                  ]
            },
            {'id': 9, 'description': 'Alternating Red-Green Light',
                'sequence': [
                    (0,0,1),
                    (1,0,0),
                    (0,0,1),
                    (1,0,0),
                    (0,0,1),
                    (1,0,0),
                    (0,0,1),
                  ]
            },
            {'id': 10, 'description': 'Red-Off-Green-Off Alternating',
                'sequence': [
                    (0,0,1),
                    (0,0,0),
                    (1,0,0),
                    (0,0,0),
                    (0,0,1),
                    (0,0,0),
                    (1,0,0),
                  ]
            },
            {'id': 11, 'description': 'Pedestrian with Green to Flashing Red to Solid Red',
                'sequence': [
                    (1,0,0),
                    (0,0,1),
                    (0,0,0),
                    (0,0,1),
                    (0,0,0),
                    (0,0,1),
                    (0,0,1),
                  ]
            },
            {'id': 12, 'description': 'Single Light Random Flashing',
                'sequence': [
                    (0,1,0),
                    (1,0,0),
                    (0,1,0),
                    (0,0,1),
                    (1,0,0),
                    (0,0,1),
                    (1,0,0),
                  ]
            },
            {'id': 13, 'description': 'Dual Light Random Flashing',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (1,0,0),
                    (1,1,0),
                    (0,1,0),
                    (0,0,1),
                    (0,1,1),
                  ]
            },
            {'id': 14, 'description': 'Single Light Random Flashing with blanking',
                'sequence': [
                    (1,0,0),
                    (0,1,0),
                    (0,0,0),
                    (0,0,1),
                    (0,0,0),
                    (1,0,0),
                    (0,0,1),
                  ]
            },
            {'id': 15, 'description': 'Sweeping Lights Down Green-Yellow-Red',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (0,1,0),
                    (1,1,0),
                    (1,0,0),
                    (0,0,1),
                    (0,1,1),
                  ]
            },
            {'id': 16, 'description': 'Sweeping Lights Up Green-Yellow-Red',
                'sequence': [
                    (1,0,0),
                    (1,1,0),
                    (0,1,0),
                    (0,1,1),
                    (0,0,1),
                    (1,0,0),
                    (1,1,0),
                  ]
            },
            {'id': 17, 'description': 'Sweeping Lights Up-Down',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (0,1,0),
                    (0,1,0),
                    (1,0,0),
                    (1,1,0),
                    (0,1,0),
                  ]
            },
            {'id': 18, 'description': 'Old Fashion ACME Traffic Light',
                'sequence': [
                    (1,0,0),
                    (1,1,0),
                    (1,1,0),
                    (1,1,0),
                    (1,1,0),
                    (1,0,0),
                    (0,0,1),
                  ]
            },
            {'id': 19, 'description': 'Old Fashion Traffic Light with change gaps',
                'sequence': [
                    (0,0,1),
                    (0,0,0),
                    (0,1,0),
                    (0,0,0),
                    (1,0,0),
                    (0,0,0),
                    (0,0,1),
                  ]
            },
            {'id': 20, 'description': 'Old Fashin Traffic Light with change overlap',
                'sequence': [
                    (0,0,1),
                    (1,0,1),
                    (1,0,0),
                    (1,1,0),
                    (0,1,0),
                    (0,1,1),
                    (0,0,1),
                  ]
            },
            {'id': 21, 'description': 'Red-Yellow-Green sweep to all On and then to all Off',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (1,1,1),
                    (0,0,0),
                    (0,0,1),
                    (0,1,1),
                    (1,1,1),
                  ]
            },
            {'id': 22, 'description': 'Red-Yellow-Green sweep to all On and then sweep to all Off',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (1,1,1),
                    (0,1,1),
                    (0,0,1),
                    (0,0,0),
                    (0,0,1),
                  ]
            },
            {'id': 23, 'description': 'Green-Yeelow-Red sweep to all On and then to all Off',
                'sequence': [
                    (1,0,0),
                    (1,1,0),
                    (1,1,1),
                    (0,0,0),
                    (1,0,0),
                    (1,1,0),
                    (1,1,1),
                  ]
            },
            {'id': 24, 'description': 'Green-Yellow-Red sweep to all On and then sweep to all Off',
                'sequence': [
                    (1,0,0),
                    (1,1,0),
                    (1,1,1),
                    (1,1,0),
                    (1,0,0),
                    (0,0,0),
                    (1,0,0),
                  ]
            },      
            {'id': 25, 'description': 'Green-Yellow-Red sweep back and forth all lights On',
                'sequence': [
                    (0,0,1),
                    (0,1,1),
                    (1,1,1),
                    (1,1,0),
                    (1,0,0),
                    (0,0,0),
                    (1,0,0),
                  ]
            },            
        ]

